
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.D365.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
public enum ComponentState
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Deleted", 2)]
  Deleted = 2,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Deleted Unpublished", 3)]
  DeletedUnpublished = 3,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Published", 0)]
  Published = 0,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Unpublished", 1)]
  Unpublished = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum IsInherited
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Direct User (Basic) access level and Team privileges", 1)]
  DirectUser_BasicaccesslevelandTeamprivileges = 1,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Team privileges only", 0)]
  Teamprivilegesonly = 0,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum SystemUser_AccessMode
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Administrative", 1)]
  Administrative = 1,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Delegated Admin", 5)]
  DelegatedAdmin = 5,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Non-interactive", 4)]
  Noninteractive = 4,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Read", 2)]
  Read = 2,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Read-Write", 0)]
  ReadWrite = 0,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Support User", 3)]
  SupportUser = 3,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum SystemUser_Address1_AddressTypeCode
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Default Value", 0)]
  DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum SystemUser_Address1_ShippingMethodCode
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Default Value", 0)]
  DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum SystemUser_Address2_AddressTypeCode
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Default Value", 0)]
  DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum SystemUser_Address2_ShippingMethodCode
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Default Value", 0)]
  DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum SystemUser_CALType
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Administrative", 1)]
  Administrative = 1,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Basic", 2)]
  Basic = 2,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Device Basic", 4)]
  DeviceBasic = 4,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Device Enterprise", 8)]
  DeviceEnterprise = 8,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Device Essential", 6)]
  DeviceEssential = 6,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Device Professional", 3)]
  DeviceProfessional = 3,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Enterprise", 7)]
  Enterprise = 7,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Essential", 5)]
  Essential = 5,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Field Service", 11)]
  FieldService = 11,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Professional", 0)]
  Professional = 0,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Project Service", 12)]
  ProjectService = 12,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Sales", 9)]
  Sales = 9,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Service", 10)]
  Service = 10,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum SystemUser_EmailRouterAccessApproval
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Approved", 1)]
  Approved = 1,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Empty", 0)]
  Empty = 0,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Pending Approval", 2)]
  PendingApproval = 2,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Rejected", 3)]
  Rejected = 3,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum SystemUser_IncomingEmailDeliveryMethod
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Forward Mailbox", 3)]
  ForwardMailbox = 3,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Microsoft Dynamics 365 for Outlook", 1)]
  MicrosoftDynamics365forOutlook = 1,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("None", 0)]
  None = 0,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Server-Side Synchronization or Email Router", 2)]
  ServerSideSynchronizationorEmailRouter = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum SystemUser_InviteStatusCode
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Invitation Accepted", 4)]
  InvitationAccepted = 4,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Invitation Expired", 3)]
  InvitationExpired = 3,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Invitation Near Expired", 2)]
  InvitationNearExpired = 2,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Invitation Not Sent", 0)]
  InvitationNotSent = 0,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Invitation Rejected", 5)]
  InvitationRejected = 5,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Invitation Revoked", 6)]
  InvitationRevoked = 6,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Invited", 1)]
  Invited = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum SystemUser_OutgoingEmailDeliveryMethod
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Microsoft Dynamics 365 for Outlook", 1)]
  MicrosoftDynamics365forOutlook = 1,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("None", 0)]
  None = 0,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Server-Side Synchronization or Email Router", 2)]
  ServerSideSynchronizationorEmailRouter = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum SystemUser_PreferredAddressCode
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Mailing Address", 0)]
  MailingAddress = 1,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Other Address", 1)]
  OtherAddress = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum SystemUser_PreferredEmailCode
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Default Value", 0)]
  DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum SystemUser_PreferredPhoneCode
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Home Phone", 2)]
  HomePhone = 3,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Main Phone", 0)]
  MainPhone = 1,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Mobile Phone", 3)]
  MobilePhone = 4,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Other Phone", 1)]
  OtherPhone = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Team_MembershipType
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Guests", 3)]
  Guests = 3,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Members", 1)]
  Members = 1,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Members and guests", 0)]
  Membersandguests = 0,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Owners", 2)]
  Owners = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Team_TeamType
{

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("AAD Office Group", 3)]
  AADOfficeGroup = 3,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("AAD Security Group", 2)]
  AADSecurityGroup = 2,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Access", 1)]
  Access = 1,

  [System.Runtime.Serialization.EnumMemberAttribute()]
  [OptionSetMetadataAttribute("Owner", 0)]
  Owner = 0,
}
}
